### ISSUE TITLE
README's keymapping issue

### ISSUE THREAD

**Issue by jelly** [ElPiloto/telescope-vimwiki.nvim#4]
```
nnoremap <leader>vw <cmd>lua require('telescope').extensions.vimwiki.vimwiki()<cr>
```

Using this as a keybinding is broken as opts would be nil.

https://github.com/ElPiloto/telescope-vimwiki.nvim/blob/0525d77c5e03b7853a6913aabbf1a960d5b12d6a/lua/telescope/_extensions/vimwiki/pickers.lua#L16

**Comment by ElPiloto** [comment]
Thank you for reporting this.
